server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

# Azure storage container config
azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: raw-videos

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info