server:
  port: 8082

# MySql database configuration
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_db
    username: root
    password: root

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: content-service-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer



      properties:
#        "[spring.json.trusted.packages]": "com.streaming_app.ContentService.Application.Events"
#        "[spring.json.use.type.headers]": false
        "[max.poll.interval.ms]": 7200000
        "[max.poll.records]": 1

  # JPA CONFIGURE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info